Revert "hack"
This reverts commit 2fbd4d2851268fc5a1d94e26f77726d195a5a92d.

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -26,8 +26,9 @@ jobs:
       - name: Fail on PR to branch other than pending
         if: github.event_name != 'merge_group' && github.base_ref != 'pending'
         run: |
-          echo "Hacked!" >&2
-          exit 0
+          echo "Must PR to pending branch!" >&2
+          echo "::error title=PR Check failed::You MUST PR to pending branch!"
+          exit 1
 
       - name: Checkout base on PR to pending
         if: github.event_name != 'merge_group' && github.base_ref == 'pending'
@@ -54,7 +55,7 @@ jobs:
           if git -C base diff --pretty= --name-only --no-renames | grep -q '^.github/workflows/'; then \
             echo "Don't HACK my workflows!" >&2; \
             echo "::error title=PR Check failed::Don't touch workflows!"; \
-            exit 0; \
+            exit 1; \
           else \
             true; \
           fi
